[".oh-my-zsh"]
    type = "git-repo"
    url = "https://github.com/ohmyzsh/ohmyzsh.git"
    exact = true
    branch = "master"
    pull.args = ["--depth", "1"]
    refreshPeriod = "168h"
    
[".omzsh-custom/plugins/zsh-syntax-highlighting"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    exact = true
    branch = "master"
    pull.args = ["--depth", "1"]
    refreshPeriod = "168h"

[".omzsh-custom/plugins/zsh-completions"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-completions/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".omzsh-custom/plugins/zsh-autosuggestions"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-autosuggestions/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".asdf"]
    type = "git-repo"
    url = "https://github.com/asdf-vm/asdf.git"
    branch = "master"
    exact = true
    pull.args = ["--depth", "1"]

[".asdf/plugins/nodejs"]
    type = "git-repo"
    exact = true
    url = "https://github.com/asdf-vm/asdf-nodejs.git"
    branch = "master"
    pull.args = ["--depth", "1"]

[".asdf/plugins/python"]
    type = "git-repo"
    exact = true
    url = "https://github.com/asdf-community/asdf-python.git"
    branch = "master"
    pull.args = ["--depth", "1"]


[".asdf/plugins/terraform"]
    type = "git-repo"
    exact = true
    url = "https://github.com/asdf-community/asdf-hashicorp.git"
    branch = "master"
    pull.args = ["--depth", "1"]
    
[".asdf/plugins/consul"]
    type = "git-repo"
    exact = true
    url = "https://github.com/asdf-community/asdf-hashicorp.git"
    branch = "master"
    pull.args = ["--depth", "1"]

[".asdf/plugins/bun"]
    type = "git-repo"
    exact = true
    url = "https://github.com/cometkim/asdf-bun.git"
    branch = "main"
    pull.args = ["--depth", "1"]

[".tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm.git"
    exact = true
    branch = "master"
    pull.args = ["--depth", "1"]
