#!/bin/zsh

CONF_PATH="${HOME}/.zshrc.d"

function source_dir() {
    for FN in $1/*; do
        # if file, directly source it
        if [ -f "$FN" ]; then
            source "$FN"
        fi

        # if directory, recursively source
        if [ -d "${FN}" ]; then
            source_dir "$FN"
        fi
    done
}

source_dir $CONF_PATH
